import { google } from "@ai-sdk/google"
import { generateText } from "ai"

export const maxDuration = 60

export async function POST(req: Request) {
  try {
    const { conversation } = await req.json()

    if (!conversation) {
      return Response.json({ error: "Missing conversation" }, { status: 400 })
    }

    const apiKey = process.env.NEXT_PUBLIC_GOOGLE_GENERATIVE_AI_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY
    if (!apiKey) {
      console.error("Google API key not found in environment")
      return Response.json({ error: "API key not configured" }, { status: 500 })
    }

    // Use Gemini text model to generate comprehensive report
    const { text: report } = await generateText({
      model: google("gemini-2.0-flash", { apiKey }),
      temperature: 0.7,
      system: `You are a professional medical report generator. Based on the patient consultation provided, generate a comprehensive, structured medical consultation report that includes:

1. PATIENT SUMMARY: Extract basic information about the patient (name, age, gender if mentioned)
2. CHIEF COMPLAINT: Main health concern
3. SYMPTOMS SUMMARY: Organized list of reported symptoms
4. MEDICAL HISTORY: Previous conditions, surgeries, medications, allergies
5. LIFESTYLE FACTORS: Smoking, alcohol, sleep, diet, exercise
6. FAMILY HISTORY: Relevant family medical conditions
7. ASSESSMENT: Analysis of symptoms and potential areas of concern (NOT a diagnosis)
8. RECOMMENDATIONS: 
   - Immediate actions
   - What specialist to see
   - Lifestyle modifications
   - When to seek emergency care
9. DISCLAIMER: Include clear disclaimer that this is AI-generated and not a substitute for professional medical advice

Format the report professionally with clear sections and bullet points. Include today's date and time. Keep it comprehensive but concise.`,
      prompt: `Generate a medical consultation report based on this patient consultation transcript:\n\n${conversation}`,
    })

    const formattedReport = `═══════════════════════════════════════════════════════════════
                    AI DOCTOR CONSULTATION REPORT
═══════════════════════════════════════════════════════════════

Generated: ${new Date().toLocaleString()}

───────────────────────────────────────────────────────────────
${report}
───────────────────────────────────────────────────────────────

DISCLAIMER
───────────────────────────────────────────────────────────────

This report is generated by an AI assistant and is for 
informational purposes only. It is NOT a substitute for professional 
medical advice, diagnosis, or treatment. 

IMPORTANT:
• Please consult a licensed physician for proper diagnosis
• This AI assessment should not be used for self-diagnosis
• Seek immediate medical attention for emergencies
• Share this report with your healthcare provider

═══════════════════════════════════════════════════════════════
    Please consult a qualified healthcare professional
═══════════════════════════════════════════════════════════════`

    return Response.json({ report: formattedReport })
  } catch (error) {
    console.error("Report generation error:", error)
    return Response.json(
      { error: "Failed to generate report", details: String(error) },
      { status: 500 }
    )
  }
}
